-- AlterTable
ALTER TABLE "EventZone" ADD COLUMN     "color" VARCHAR(7),
ADD COLUMN     "height" DOUBLE PRECISION NOT NULL DEFAULT 150,
ADD COLUMN     "width" DOUBLE PRECISION NOT NULL DEFAULT 200,
ADD COLUMN     "x" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "y" DOUBLE PRECISION NOT NULL DEFAULT 0;
